//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BillionaireStocksModel", "FK_Billionaire", "Billionaire", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BillionaireStocksAPI.Billionaire), "BillionaireStock", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BillionaireStocksAPI.BillionaireStock), true)]
[assembly: EdmRelationshipAttribute("BillionaireStocksModel", "FK_BillionaireStockPrice_BillionaireStock", "BillionaireStock", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BillionaireStocksAPI.BillionaireStock), "BillionaireStockPrice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BillionaireStocksAPI.BillionaireStockPrice), true)]

#endregion

namespace BillionaireStocksAPI
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BillionaireStocksEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BillionaireStocksEntities object using the connection string found in the 'BillionaireStocksEntities' section of the application configuration file.
        /// </summary>
        public BillionaireStocksEntities() : base("name=BillionaireStocksEntities", "BillionaireStocksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BillionaireStocksEntities object.
        /// </summary>
        public BillionaireStocksEntities(string connectionString) : base(connectionString, "BillionaireStocksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BillionaireStocksEntities object.
        /// </summary>
        public BillionaireStocksEntities(EntityConnection connection) : base(connection, "BillionaireStocksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Billionaire> Billionaires
        {
            get
            {
                if ((_Billionaires == null))
                {
                    _Billionaires = base.CreateObjectSet<Billionaire>("Billionaires");
                }
                return _Billionaires;
            }
        }
        private ObjectSet<Billionaire> _Billionaires;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BillionaireStock> BillionaireStocks
        {
            get
            {
                if ((_BillionaireStocks == null))
                {
                    _BillionaireStocks = base.CreateObjectSet<BillionaireStock>("BillionaireStocks");
                }
                return _BillionaireStocks;
            }
        }
        private ObjectSet<BillionaireStock> _BillionaireStocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BillionaireStockPrice> BillionaireStockPrices
        {
            get
            {
                if ((_BillionaireStockPrices == null))
                {
                    _BillionaireStockPrices = base.CreateObjectSet<BillionaireStockPrice>("BillionaireStockPrices");
                }
                return _BillionaireStockPrices;
            }
        }
        private ObjectSet<BillionaireStockPrice> _BillionaireStockPrices;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Billionaires EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBillionaires(Billionaire billionaire)
        {
            base.AddObject("Billionaires", billionaire);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BillionaireStocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBillionaireStocks(BillionaireStock billionaireStock)
        {
            base.AddObject("BillionaireStocks", billionaireStock);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BillionaireStockPrices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBillionaireStockPrices(BillionaireStockPrice billionaireStockPrice)
        {
            base.AddObject("BillionaireStockPrices", billionaireStockPrice);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BillionaireStocksModel", Name="Billionaire")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Billionaire : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Billionaire object.
        /// </summary>
        /// <param name="billionaireId">Initial value of the BillionaireId property.</param>
        public static Billionaire CreateBillionaire(global::System.Int32 billionaireId)
        {
            Billionaire billionaire = new Billionaire();
            billionaire.BillionaireId = billionaireId;
            return billionaire;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BillionaireId
        {
            get
            {
                return _BillionaireId;
            }
            set
            {
                if (_BillionaireId != value)
                {
                    OnBillionaireIdChanging(value);
                    ReportPropertyChanging("BillionaireId");
                    _BillionaireId = StructuralObject.SetValidValue(value, "BillionaireId");
                    ReportPropertyChanged("BillionaireId");
                    OnBillionaireIdChanged();
                }
            }
        }
        private global::System.Int32 _BillionaireId;
        partial void OnBillionaireIdChanging(global::System.Int32 value);
        partial void OnBillionaireIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillionaireFirstName
        {
            get
            {
                return _BillionaireFirstName;
            }
            set
            {
                OnBillionaireFirstNameChanging(value);
                ReportPropertyChanging("BillionaireFirstName");
                _BillionaireFirstName = StructuralObject.SetValidValue(value, true, "BillionaireFirstName");
                ReportPropertyChanged("BillionaireFirstName");
                OnBillionaireFirstNameChanged();
            }
        }
        private global::System.String _BillionaireFirstName;
        partial void OnBillionaireFirstNameChanging(global::System.String value);
        partial void OnBillionaireFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillionaireLastName
        {
            get
            {
                return _BillionaireLastName;
            }
            set
            {
                OnBillionaireLastNameChanging(value);
                ReportPropertyChanging("BillionaireLastName");
                _BillionaireLastName = StructuralObject.SetValidValue(value, true, "BillionaireLastName");
                ReportPropertyChanged("BillionaireLastName");
                OnBillionaireLastNameChanged();
            }
        }
        private global::System.String _BillionaireLastName;
        partial void OnBillionaireLastNameChanging(global::System.String value);
        partial void OnBillionaireLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillionaireCompany
        {
            get
            {
                return _BillionaireCompany;
            }
            set
            {
                OnBillionaireCompanyChanging(value);
                ReportPropertyChanging("BillionaireCompany");
                _BillionaireCompany = StructuralObject.SetValidValue(value, true, "BillionaireCompany");
                ReportPropertyChanged("BillionaireCompany");
                OnBillionaireCompanyChanged();
            }
        }
        private global::System.String _BillionaireCompany;
        partial void OnBillionaireCompanyChanging(global::System.String value);
        partial void OnBillionaireCompanyChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BillionaireStocksModel", "FK_Billionaire", "BillionaireStock")]
        public EntityCollection<BillionaireStock> BillionaireStocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BillionaireStock>("BillionaireStocksModel.FK_Billionaire", "BillionaireStock");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BillionaireStock>("BillionaireStocksModel.FK_Billionaire", "BillionaireStock", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BillionaireStocksModel", Name="BillionaireStock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BillionaireStock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BillionaireStock object.
        /// </summary>
        /// <param name="billionaireStockId">Initial value of the BillionaireStockId property.</param>
        public static BillionaireStock CreateBillionaireStock(global::System.Int32 billionaireStockId)
        {
            BillionaireStock billionaireStock = new BillionaireStock();
            billionaireStock.BillionaireStockId = billionaireStockId;
            return billionaireStock;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BillionaireStockId
        {
            get
            {
                return _BillionaireStockId;
            }
            set
            {
                if (_BillionaireStockId != value)
                {
                    OnBillionaireStockIdChanging(value);
                    ReportPropertyChanging("BillionaireStockId");
                    _BillionaireStockId = StructuralObject.SetValidValue(value, "BillionaireStockId");
                    ReportPropertyChanged("BillionaireStockId");
                    OnBillionaireStockIdChanged();
                }
            }
        }
        private global::System.Int32 _BillionaireStockId;
        partial void OnBillionaireStockIdChanging(global::System.Int32 value);
        partial void OnBillionaireStockIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillionaireStockTicker
        {
            get
            {
                return _BillionaireStockTicker;
            }
            set
            {
                OnBillionaireStockTickerChanging(value);
                ReportPropertyChanging("BillionaireStockTicker");
                _BillionaireStockTicker = StructuralObject.SetValidValue(value, true, "BillionaireStockTicker");
                ReportPropertyChanged("BillionaireStockTicker");
                OnBillionaireStockTickerChanged();
            }
        }
        private global::System.String _BillionaireStockTicker;
        partial void OnBillionaireStockTickerChanging(global::System.String value);
        partial void OnBillionaireStockTickerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillionaireStockCompany
        {
            get
            {
                return _BillionaireStockCompany;
            }
            set
            {
                OnBillionaireStockCompanyChanging(value);
                ReportPropertyChanging("BillionaireStockCompany");
                _BillionaireStockCompany = StructuralObject.SetValidValue(value, true, "BillionaireStockCompany");
                ReportPropertyChanged("BillionaireStockCompany");
                OnBillionaireStockCompanyChanged();
            }
        }
        private global::System.String _BillionaireStockCompany;
        partial void OnBillionaireStockCompanyChanging(global::System.String value);
        partial void OnBillionaireStockCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BillionaireStockBoughtDate
        {
            get
            {
                return _BillionaireStockBoughtDate;
            }
            set
            {
                OnBillionaireStockBoughtDateChanging(value);
                ReportPropertyChanging("BillionaireStockBoughtDate");
                _BillionaireStockBoughtDate = StructuralObject.SetValidValue(value, "BillionaireStockBoughtDate");
                ReportPropertyChanged("BillionaireStockBoughtDate");
                OnBillionaireStockBoughtDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BillionaireStockBoughtDate;
        partial void OnBillionaireStockBoughtDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBillionaireStockBoughtDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BillionaireStockSoldDate
        {
            get
            {
                return _BillionaireStockSoldDate;
            }
            set
            {
                OnBillionaireStockSoldDateChanging(value);
                ReportPropertyChanging("BillionaireStockSoldDate");
                _BillionaireStockSoldDate = StructuralObject.SetValidValue(value, "BillionaireStockSoldDate");
                ReportPropertyChanged("BillionaireStockSoldDate");
                OnBillionaireStockSoldDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BillionaireStockSoldDate;
        partial void OnBillionaireStockSoldDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBillionaireStockSoldDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BillionaireStockPricePaid
        {
            get
            {
                return _BillionaireStockPricePaid;
            }
            set
            {
                OnBillionaireStockPricePaidChanging(value);
                ReportPropertyChanging("BillionaireStockPricePaid");
                _BillionaireStockPricePaid = StructuralObject.SetValidValue(value, "BillionaireStockPricePaid");
                ReportPropertyChanged("BillionaireStockPricePaid");
                OnBillionaireStockPricePaidChanged();
            }
        }
        private Nullable<global::System.Decimal> _BillionaireStockPricePaid;
        partial void OnBillionaireStockPricePaidChanging(Nullable<global::System.Decimal> value);
        partial void OnBillionaireStockPricePaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BillionaireStockPriceSold
        {
            get
            {
                return _BillionaireStockPriceSold;
            }
            set
            {
                OnBillionaireStockPriceSoldChanging(value);
                ReportPropertyChanging("BillionaireStockPriceSold");
                _BillionaireStockPriceSold = StructuralObject.SetValidValue(value, "BillionaireStockPriceSold");
                ReportPropertyChanged("BillionaireStockPriceSold");
                OnBillionaireStockPriceSoldChanged();
            }
        }
        private Nullable<global::System.Decimal> _BillionaireStockPriceSold;
        partial void OnBillionaireStockPriceSoldChanging(Nullable<global::System.Decimal> value);
        partial void OnBillionaireStockPriceSoldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BillionaireId
        {
            get
            {
                return _BillionaireId;
            }
            set
            {
                OnBillionaireIdChanging(value);
                ReportPropertyChanging("BillionaireId");
                _BillionaireId = StructuralObject.SetValidValue(value, "BillionaireId");
                ReportPropertyChanged("BillionaireId");
                OnBillionaireIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BillionaireId;
        partial void OnBillionaireIdChanging(Nullable<global::System.Int32> value);
        partial void OnBillionaireIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DividendYield
        {
            get
            {
                return _DividendYield;
            }
            set
            {
                OnDividendYieldChanging(value);
                ReportPropertyChanging("DividendYield");
                _DividendYield = StructuralObject.SetValidValue(value, "DividendYield");
                ReportPropertyChanged("DividendYield");
                OnDividendYieldChanged();
            }
        }
        private Nullable<global::System.Double> _DividendYield;
        partial void OnDividendYieldChanging(Nullable<global::System.Double> value);
        partial void OnDividendYieldChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BillionaireStocksModel", "FK_Billionaire", "Billionaire")]
        public Billionaire Billionaire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Billionaire>("BillionaireStocksModel.FK_Billionaire", "Billionaire").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Billionaire>("BillionaireStocksModel.FK_Billionaire", "Billionaire").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Billionaire> BillionaireReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Billionaire>("BillionaireStocksModel.FK_Billionaire", "Billionaire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Billionaire>("BillionaireStocksModel.FK_Billionaire", "Billionaire", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BillionaireStocksModel", "FK_BillionaireStockPrice_BillionaireStock", "BillionaireStockPrice")]
        public EntityCollection<BillionaireStockPrice> BillionaireStockPrices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BillionaireStockPrice>("BillionaireStocksModel.FK_BillionaireStockPrice_BillionaireStock", "BillionaireStockPrice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BillionaireStockPrice>("BillionaireStocksModel.FK_BillionaireStockPrice_BillionaireStock", "BillionaireStockPrice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BillionaireStocksModel", Name="BillionaireStockPrice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BillionaireStockPrice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BillionaireStockPrice object.
        /// </summary>
        /// <param name="billionaireStockPriceId">Initial value of the BillionaireStockPriceId property.</param>
        public static BillionaireStockPrice CreateBillionaireStockPrice(global::System.Int32 billionaireStockPriceId)
        {
            BillionaireStockPrice billionaireStockPrice = new BillionaireStockPrice();
            billionaireStockPrice.BillionaireStockPriceId = billionaireStockPriceId;
            return billionaireStockPrice;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BillionaireStockPriceId
        {
            get
            {
                return _BillionaireStockPriceId;
            }
            set
            {
                if (_BillionaireStockPriceId != value)
                {
                    OnBillionaireStockPriceIdChanging(value);
                    ReportPropertyChanging("BillionaireStockPriceId");
                    _BillionaireStockPriceId = StructuralObject.SetValidValue(value, "BillionaireStockPriceId");
                    ReportPropertyChanged("BillionaireStockPriceId");
                    OnBillionaireStockPriceIdChanged();
                }
            }
        }
        private global::System.Int32 _BillionaireStockPriceId;
        partial void OnBillionaireStockPriceIdChanging(global::System.Int32 value);
        partial void OnBillionaireStockPriceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BillionaireStockPriceValue
        {
            get
            {
                return _BillionaireStockPriceValue;
            }
            set
            {
                OnBillionaireStockPriceValueChanging(value);
                ReportPropertyChanging("BillionaireStockPriceValue");
                _BillionaireStockPriceValue = StructuralObject.SetValidValue(value, "BillionaireStockPriceValue");
                ReportPropertyChanged("BillionaireStockPriceValue");
                OnBillionaireStockPriceValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _BillionaireStockPriceValue;
        partial void OnBillionaireStockPriceValueChanging(Nullable<global::System.Decimal> value);
        partial void OnBillionaireStockPriceValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BillionaireStockPriceDate
        {
            get
            {
                return _BillionaireStockPriceDate;
            }
            set
            {
                OnBillionaireStockPriceDateChanging(value);
                ReportPropertyChanging("BillionaireStockPriceDate");
                _BillionaireStockPriceDate = StructuralObject.SetValidValue(value, "BillionaireStockPriceDate");
                ReportPropertyChanged("BillionaireStockPriceDate");
                OnBillionaireStockPriceDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BillionaireStockPriceDate;
        partial void OnBillionaireStockPriceDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBillionaireStockPriceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BillionaireStockId
        {
            get
            {
                return _BillionaireStockId;
            }
            set
            {
                OnBillionaireStockIdChanging(value);
                ReportPropertyChanging("BillionaireStockId");
                _BillionaireStockId = StructuralObject.SetValidValue(value, "BillionaireStockId");
                ReportPropertyChanged("BillionaireStockId");
                OnBillionaireStockIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BillionaireStockId;
        partial void OnBillionaireStockIdChanging(Nullable<global::System.Int32> value);
        partial void OnBillionaireStockIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BillionaireStocksModel", "FK_BillionaireStockPrice_BillionaireStock", "BillionaireStock")]
        public BillionaireStock BillionaireStock
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BillionaireStock>("BillionaireStocksModel.FK_BillionaireStockPrice_BillionaireStock", "BillionaireStock").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BillionaireStock>("BillionaireStocksModel.FK_BillionaireStockPrice_BillionaireStock", "BillionaireStock").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BillionaireStock> BillionaireStockReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BillionaireStock>("BillionaireStocksModel.FK_BillionaireStockPrice_BillionaireStock", "BillionaireStock");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BillionaireStock>("BillionaireStocksModel.FK_BillionaireStockPrice_BillionaireStock", "BillionaireStock", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
